/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SeloImage {
        "alt"?: string;
        "src"?: string;
    }
    interface SeloImageSharp {
        "alt"?: string;
        "height": number;
        "src"?: string;
        "width": number;
    }
}
declare global {
    interface HTMLSeloImageElement extends Components.SeloImage, HTMLStencilElement {
    }
    var HTMLSeloImageElement: {
        prototype: HTMLSeloImageElement;
        new (): HTMLSeloImageElement;
    };
    interface HTMLSeloImageSharpElement extends Components.SeloImageSharp, HTMLStencilElement {
    }
    var HTMLSeloImageSharpElement: {
        prototype: HTMLSeloImageSharpElement;
        new (): HTMLSeloImageSharpElement;
    };
    interface HTMLElementTagNameMap {
        "selo-image": HTMLSeloImageElement;
        "selo-image-sharp": HTMLSeloImageSharpElement;
    }
}
declare namespace LocalJSX {
    interface SeloImage {
        "alt"?: string;
        /**
          * Emitted when the img fails to load
         */
        "onIonError"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the image has finished loading
         */
        "onIonImgDidLoad"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the img src has been set
         */
        "onIonImgWillLoad"?: (event: CustomEvent<void>) => void;
        "src"?: string;
    }
    interface SeloImageSharp {
        "alt"?: string;
        "height"?: number;
        "src"?: string;
        "width"?: number;
    }
    interface IntrinsicElements {
        "selo-image": SeloImage;
        "selo-image-sharp": SeloImageSharp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "selo-image": LocalJSX.SeloImage & JSXBase.HTMLAttributes<HTMLSeloImageElement>;
            "selo-image-sharp": LocalJSX.SeloImageSharp & JSXBase.HTMLAttributes<HTMLSeloImageSharpElement>;
        }
    }
}
