/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ImageOptions, Source } from "./utils/models";
export namespace Components {
    interface SeloImg {
        "alt"?: string;
        "sizes"?: string;
        "sources": Array<Source>;
        "src"?: string;
        "srcset"?: string;
        "type": string;
    }
    interface SeloImgSharp {
        "options": ImageOptions | any;
    }
}
declare global {
    interface HTMLSeloImgElement extends Components.SeloImg, HTMLStencilElement {
    }
    var HTMLSeloImgElement: {
        prototype: HTMLSeloImgElement;
        new (): HTMLSeloImgElement;
    };
    interface HTMLSeloImgSharpElement extends Components.SeloImgSharp, HTMLStencilElement {
    }
    var HTMLSeloImgSharpElement: {
        prototype: HTMLSeloImgSharpElement;
        new (): HTMLSeloImgSharpElement;
    };
    interface HTMLElementTagNameMap {
        "selo-img": HTMLSeloImgElement;
        "selo-img-sharp": HTMLSeloImgSharpElement;
    }
}
declare namespace LocalJSX {
    interface SeloImg {
        "alt"?: string;
        /**
          * Emitted when the image has finished loading
         */
        "onImgDidLoad"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the img fails to load
         */
        "onImgError"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the img src has been set
         */
        "onImgWillLoad"?: (event: CustomEvent<void>) => void;
        "sizes"?: string;
        "sources"?: Array<Source>;
        "src"?: string;
        "srcset"?: string;
        "type"?: string;
    }
    interface SeloImgSharp {
        "options"?: ImageOptions | any;
    }
    interface IntrinsicElements {
        "selo-img": SeloImg;
        "selo-img-sharp": SeloImgSharp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "selo-img": LocalJSX.SeloImg & JSXBase.HTMLAttributes<HTMLSeloImgElement>;
            "selo-img-sharp": LocalJSX.SeloImgSharp & JSXBase.HTMLAttributes<HTMLSeloImgSharpElement>;
        }
    }
}
